export const SPAAACE = {
  "Terrestrial planets": [
    {
      Name: "Mercury",
      Mass: 0.33,
      Diameter: 4879,
      Density: 5427,
      Gravity: 3.7,
      "Length of day": 4222.6,
      "Distance from Sun": 57.9,
      "Mean temperature": 167,
      "Number of moons": 0,
      Notes: "Closest to the Sun",
    },
    {
      Name: "Venus",
      Mass: 4.87,
      Diameter: 12104,
      Density: 5243,
      Gravity: 8.9,
      "Length of day": 2802.0,
      "Distance from Sun": 108.2,
      "Mean temperature": 464,
      "Number of moons": 0,
      Notes: "",
    },
    {
      Name: "Earth",
      Mass: 5.97,
      Diameter: 12756,
      Density: 5514,
      Gravity: 9.8,
      "Length of day": 24.0,
      "Distance from Sun": 149.6,
      "Mean temperature": 15,
      "Number of moons": 1,
      Notes: "Our world",
    },
    {
      Name: "Mars",
      Mass: 0.642,
      Diameter: 6792,
      Density: 3933,
      Gravity: 3.7,
      "Length of day": 24.7,
      "Distance from Sun": 227.9,
      "Mean temperature": -65,
      "Number of moons": 2,
      Notes: "The red planet",
    },
  ],
  "Jovian planets": {
    "Gas giants": [
      {
        Name: "Jupiter",
        Mass: 1898,
        Diameter: 142984,
        Density: 1326,
        Gravity: 23.1,
        "Length of day": 9.9,
        "Distance from Sun": 778.6,
        "Mean temperature": -110,
        "Number of moons": 67,
        Notes: "The largest planet",
      },
      {
        Name: "Saturn",
        Mass: 568,
        Diameter: 120536,
        Density: 687,
        Gravity: 9.0,
        "Length of day": 10.7,
        "Distance from Sun": 1433.5,
        "Mean temperature": -140,
        "Number of moons": 62,
        Notes: "",
      },
    ],
    "Ice giants": [
      {
        Name: "Uranus",
        Mass: 86.8,
        Diameter: 51118,
        Density: 1271,
        Gravity: 8.7,
        "Length of day": 17.2,
        "Distance from Sun": 2872.5,
        "Mean temperature": -195,
        "Number of moons": 27,
        Notes: "",
      },
      {
        Name: "Neptune",
        Mass: 102,
        Diameter: 49528,
        Density: 1638,
        Gravity: 11.0,
        "Length of day": 16.1,
        "Distance from Sun": 4495.1,
        "Mean temperature": -200,
        "Number of moons": 14,
        Notes: "",
      },
    ],
  },
  "Dwarf planets": [
    {
      Name: "Pluto",
      Mass: 0.0146,
      Diameter: 2370,
      Density: 2095,
      Gravity: 0.7,
      "Length of day": 153.3,
      "Distance from Sun": 5906.4,
      "Mean temperature": -225,
      "Number of moons": 5,
      Notes: "Declassified as a planet in 2006, but this remains controversial",
    },
    {
      Name: "Eris",
      Mass: 0.0167,
      Diameter: 2326,
      Density: 2440,
      Gravity: 0.8,
      "Length of day": 25.9,
      "Distance from Sun": 10100.0,
      "Mean temperature": -231,
      "Number of moons": 1,
      Notes: "More massive than Pluto",
    },
    {
      Name: "Haumea",
      Mass: 0.004,
      Diameter: 1960,
      Density: 2610,
      Gravity: 0.44,
      "Length of day": 3.9,
      "Distance from Sun": 6484.0,
      "Mean temperature": -241,
      "Number of moons": 2,
      Notes: "Elliptical shape due to fast rotation",
    },
    {
      Name: "Makemake",
      Mass: 0.003,
      Diameter: 1430,
      Density: 1600,
      Gravity: 0.5,
      "Length of day": 22.5,
      "Distance from Sun": 6850.0,
      "Mean temperature": -239,
      "Number of moons": 1,
      Notes: "Named after a Rapa Nui deity",
    },
    {
      Name: "Ceres",
      Mass: 0.000938,
      Diameter: 946,
      Density: 2160,
      Gravity: 0.27,
      "Length of day": 9.1,
      "Distance from Sun": 413.7,
      "Mean temperature": -105,
      "Number of moons": 0,
      Notes: "Located in the asteroid belt",
    },
  ],
  Moons: [
    {
      Name: "Moon",
      Mass: 0.073,
      Diameter: 3474,
      Density: 3340,
      Gravity: 1.6,
      "Length of day": 655.7,
      "Distance from Sun": 149.6,
      "Mean temperature": -20,
      "Number of moons": 0,
      Notes: "Earth's only natural satellite",
    },
    {
      Name: "Ganymede",
      Mass: 0.148,
      Diameter: 5268,
      Density: 1940,
      Gravity: 1.43,
      "Length of day": 171.7,
      "Distance from Sun": 778.6,
      "Mean temperature": -163,
      "Number of moons": 0,
      Notes: "Largest moon in the solar system",
    },
    {
      Name: "Titan",
      Mass: 0.1345,
      Diameter: 5150,
      Density: 1880,
      Gravity: 1.35,
      "Length of day": 382.7,
      "Distance from Sun": 1433.5,
      "Mean temperature": -179,
      "Number of moons": 0,
      Notes: "Only moon with a dense atmosphere",
    },
  ],
};
